project:
  type: website
  resources:
       - /scss-posts.scss
  render:
        - "*.qmd"
  output-dir: "docs"
website:
  title: ""
  page-footer:
    background: "#121212"
    left: |
      [2026]()
    center:
      - href: https://github.com/data-soc/datasoc-website
        target: _blank
        icon: github
        aria-label: GitHub
    # right: |
    #    Last Update: {{< modified isodate>}}
  navbar:
    logo: resources/imagenes/logo-nobg.png
    background: "#FFFFFF"
    # tools: 
    #    - icon: github
    #      href: https://github.com/datasoc/
    #      target: _blank
    #    - icon: globe
    #      href: https://facso.uchile.cl/
    #      target: _blank
    #    - icon: twitter
    #      href: https://x.com/facsouchile
    #      target: _blank
    #    - icon: instagram
    #      href: https://www.instagram.com/facsouchile
    #      target: _blank
    #    - icon: youtube
    #      href: https://www.youtube.com/user/webfacso
    #      target: _blank
    # pinned: true
    right:
      - href: index.qmd#lineash1
        text: "<i class='bi bi-hexagon-fill'></i> Líneas de Trabajo"
      - href: index.qmd#proyectosh1
        text: "<i class='bi bi-briefcase-fill'></i> Proyectos y Reportes"
      - href: index.qmd#noticiash1
        text: "<i class='bi bi-newspaper'></i> Noticias"
format:
  html:
    theme: 
      light: flatly
    css: 
      - styles.css
    toc: true
    linkcolor: "#497BBD"
include-after-body: "footer.html"




