project:
  type: website
  resources:
       - /scss-posts.scss
  render:
        - "*.qmd"
  output-dir: "docs"
website:
  title: ""
  page-footer:
    background: "#121212"
    left: |
      [2026]()
    center:
      - href: https://github.com/data-soc/datasoc-website
        target: _blank
        icon: github
        aria-label: GitHub
    # right: |
    #    Last Update: {{< modified isodate>}}
  navbar:
    logo: resources/imagenes/datasoc.png
    background: "#FFFFFF"
    tools: 
       - icon: github
         href: https://github.com/datasoc/
         target: _blank
       - icon: globe
         href: https://facso.uchile.cl/
         target: _blank
       - icon: twitter
         href: https://x.com/facsouchile
         target: _blank
       - icon: instagram
         href: https://www.instagram.com/facsouchile
         target: _blank
       - icon: youtube
         href: https://www.youtube.com/user/webfacso
         target: _blank
    # pinned: true
    # left:
    #   - href: index.qmd#destacadosh1
    #     text: "<i class='bi bi-pin-angle'></i> Destacados"
    #   - href: index.qmd#analisish1
    #     text: "<i class='bi bi-graph-up-arrow'></i> Análisis"
    #   - href: index.qmd#noticiash1
    #     text: "<i class='bi bi-newspaper'></i> Noticias"
    #   - href: index.qmd#reportesh1
    #     text: "<i class='bi bi-journals'></i> Reportes"
    #   - href: index.qmd#equipoh1
    #     text: "<i class='bi bi-people-fill'></i> Equipo"
    #   - href: links.qmd
    #     text: "<i class='bi bi-link-45deg'></i> Enlaces"
format:
  html:
    theme: 
      light: flatly
    css: 
      - styles.css
    toc: true
    linkcolor: "#497BBD"
include-after-body: "footer.html"




